// ==UserScript==
// @name         Dark theme for Odoo
// @icon         http://raw.githubusercontent.com/Maurin3/userscripts/master/images/doo.png
// @namespace    http://tampermonkey.net/
// @version      0.1.0
// @description  Make all odoo.com domains dark (local version too)
// @author       Maurin3
// @include      https://www.*.odoo.com/*
// @include      https://www.*.dev.odoo.com/*
// @include      https://*.odoo.com/*
// @include      https://*.runbot*.odoo.com/*
// @include      https://www.odoo.com/*
// @include      http://localhost:8069/*
// @run-at       document-start
// @grant        none
// @downloadURL  https://raw.githubusercontent.com/Maurin3/userscripts/master/dark-odoo.user.js
// @updateURL    https://raw.githubusercontent.com/Maurin3/userscripts/master/dark-odoo.user.js
// ==/UserScript==

//Does not work on runbots

(function() {var css = "";
if (false || (document.domain == "odoo.com" || document.domain.substring(document.domain.indexOf(".odoo.com") + 1) == "odoo.com") ||(new RegExp("((http|https)://)?(www[.])?odoo.com/.+")).test(document.location.href) || (new RegExp("((http|https)://)?localhost:8069/.+")).test(document.location.href))
    css += [
        "body{",
        "    background-color: #1a1a1a;",
        "    color: #a6a6a6;",
        "}",
        "h1, h2, h3, h4, h5, h6, .h1, .h2, .h3, .h4, .h5, .h6 {",
        "    color: #9ca6b0;",
        "}",
        "a{",
        "    color: #00b3b0;",
        "}",
        "a:hover{",
        "    color: #008784;",
        "}",
        ".table th, .table td {",
        "    border-top: 1px solid #6e8091;",
        "}",
        ".table thead th {",
        "    border-top: 2px solid #6e8091;",
        "}",
        ".table tbody + tbody {",
        "    border-top: 2px solid #6e8091;",
        "}",
        ".table .table {",
        "    background-color: #1a1a1a;",
        "}",
        ".table-bordered {",
        "    border: 1px solid #6e8091;",
        "}",
        ".table-bordered th, .table-bordered td {",
        "    border-bottom: 1px solid #6e8091;",
        "}",
        ".table-primary, .table-primary > th, .table-primary > td {",
        "    background-color: #2a6f6f;", 
        "}",
        ".table-hover .table-primary:hover {",
        "    background-color: #389494;", 
        "}",
        ".table-hover .table-primary:hover > td, .table-hover .table-primary:hover > th {",
        "    background-color: #389494;", 
        "}",
        ".table-secondary, .table-secondary > th, .table-secondary > td {",
        "    background-color: #484c51;", 
        "}",
        ".table-hover .table-secondary:hover {",
        "    background-color: #60656c;", 
        "}",
        ".table-hover .table-secondary:hover > td, .table-hover .table-secondary:hover > th{",
        "    background-color: #60656c;", 
        "}",
        ".table-success, .table-success > th, .table-success > td {",
        "    background-color: #2a6f49;", 
        "}",
        ".table-hover .table-success:hover  {",
        "    background-color: #389461;", 
        "}",
        ".table-hover .table-success:hover > td, .table-hover .table-success:hover > th{",
        "    background-color: #389461;", 
        "}",
        ".table-info, .table-info > th, .table-info > td {",
        "    background-color: #2a5f6f;", 
        "}",
        ".table-hover .table-info:hover {",
        "    background-color: #387e94;", 
        "}",
        ".table-hover .table-info:hover > td, .table-hover .table-info:hover > th {",
        "    background-color: #387e94;", 
        "}",
        ".table-warning, .table-warning > th, .table-warning > td{",
        "    background-color: #8e570b;", 
        "}",
        ".table-hover .table-warning:hover {",
        "    background-color: #bd740f;", 
        "}",
        ".table-hover .table-warning:hover > td, .table-hover .table-warning:hover > th {",
        "    background-color: #bd740f;", 
        "}",
        ".table-danger, .table-danger > th, .table-danger > td {",
        "    background-color: #7c201d;", 
        "}",
        ".table-hover .table-danger:hover {",
        "    background-color: #a52b27;", 
        "}",
        ".table-hover .table-danger:hover > td, .table-hover .table-danger:hover > th {",
        "    background-color: #a52b27;", 
        "}",
        ".table-light, .table-light > th, .table-light > td {",
        "    background-color: #333366;", 
        "}",
        ".table-hover .table-light:hover {",
        "    background-color: #444488;", 
        "}",
        ".table-hover .table-light:hover > td, .table-hover .table-light:hover > th {",
        "    background-color: #444488;", 
        "}",
        ".table-dark, .table-dark > th, .table-dark > td {",
        "    background-color: #494d50;", 
        "}",
        ".table-hover .table-dark:hover {",
        "    background-color: #62666a;", 
        "}",
        ".table-hover .table-dark:hover > td, .table-hover .table-dark:hover > th {",
        "    background-color: #62666a;", 
        "}",
        ".table-default, .table-default > th, .table-default > td {",
        "    background-color: #494950;", 
        "}",
        ".table-hover .table-default:hover {",
        "    background-color: #61616b;", 
        "}",
        ".table-hover .table-default:hover > td, .table-hover .table-default:hover > th {",
        "    background-color: #61616b;", 
        "}",
        ".table-violet-dark, .table-violet-dark > th, .table-violet-dark > td {",
        "    background-color: #584152;", 
        "}",
        ".table-hover .table-violet-dark:hover {",
        "    background-color: #75576e;", 
        "}",
        ".table-hover .table-violet-dark:hover > td, .table-hover .table-violet-dark:hover > th {",
        "    background-color: #75576e;", 
        "}",
        ".table-violet-darker, .table-violet-darker > th, .table-violet-darker > td {",
        "    background-color: #52474f;", 
        "}",
        ".table-hover .table-violet-darker:hover {",
        "    background-color: #6d5f69;", 
        "}",
        ".table-hover .table-violet-darker:hover > td, .table-hover .table-violet-darker:hover > th  {",
        "    background-color: #6d5f69;", 
        "}",
        ".table-inverse-lightest, .table-inverse-lightest > th, .table-inverse-lightest > td {",
        "    background-color: #424e57;", 
        "}",
        ".table-hover .table-inverse-lightest:hover {",
        "    background-color: #586874;", 
        "}",
        ".table-hover .table-inverse-lightest:hover > td, .table-hover .table-inverse-lightest:hover > th  {",
        "    background-color: #586874;", 
        "}",
        "table-inverse-light, .table-inverse-light > th, .table-inverse-light > td {",
        "    background-color: #464e53;", 
        "}",
        ".table-hover .table-inverse-light:hover > td, .table-hover .table-inverse-light:hover > th {",
        "    background-color: #5e686e;", 
        "}",
        ".table-hover .table-inverse-light:hover {",
        "    background-color: #5e686e;", 
        "}",
        ".table-inverse, .table-inverse > th, .table-inverse > td {",
        "    background-color: #464d53;", 
        "}",
        ".table-hover .table-inverse:hover {",
        "    background-color: #5e676e;", 
        "}",
        ".table-hover .table-inverse:hover > td, .table-hover .table-inverse:hover > th {",
        "    background-color: #5e676e;", 
        "}",
        ".table-inverse-dark, .table-inverse-dark > th, .table-inverse-dark > td  {",
        "    background-color: #415058;", 
        "}",
        ".table-hover .table-inverse-dark:hover {",
        "    background-color: #576b75;", 
        "}",
        ".table-hover .table-inverse-dark:hover > td, .table-hover .table-inverse-dark:hover > th {",
        "    background-color: #576b75;", 
        "}",
        ".table-inverse-darker, .table-inverse-darker > th, .table-inverse-darker > td {",
        "    background-color: #474d52;", 
        "}",
        ".table-hover .table-inverse-darker:hover {",
        "    background-color: #5f676d;", 
        "}",
        ".table-hover .table-inverse-darker:hover > td, .table-hover .table-inverse-darker:hover > th  {",
        "    background-color: #5f676d;", 
        "}",
        ".table-alpha, .table-alpha > th, .table-alpha > td {",
        "    background-color: #2a6f6f;",
        "}",
        ".table-hover .table-alpha:hover {",
        "    background-color: #389494;",
        "}",
        ".table-hover .table-alpha:hover > td, .table-hover .table-alpha:hover > th {",
        "    background-color: #389494;",
        "}",
        ".table-alpha-dark, .table-alpha-dark > th, .table-alpha-dark > td {",
        "    background-color: #35645b;",
        "}",
        ".table-hover .table-alpha-dark:hover {",
        "    background-color: #468679;",
        "}",
        ".table-hover .table-alpha-dark:hover > td, .table-hover .table-alpha-dark:hover > th {",
        "    background-color: #468679;",
        "}",
        ".table-alpha-light, .table-alpha-light > th, .table-alpha-light > td {",
        "    background-color: #1b7e6c;",
        "}",
        ".table-hover .table-alpha-light:hover {",
        "    background-color: #24a890;",
        "}",
        ".table-hover .table-alpha-light:hover > td, .table-hover .table-alpha-light:hover > th {",
        "    background-color: #24a890;",
        "}",
        ".table-alpha-lightest, .table-alpha-lightest > th, .table-alpha-lightest > td {",
        "    background-color: #0e8b72;",
        "}",
        ".table-hover .table-alpha-lightest:hover {",
        "    background-color: #12ba98;",
        "}",
        ".table-hover .table-alpha-lightest:hover > td, .table-hover .table-alpha-lightest:hover > th {",
        "    background-color: #12ba98;",
        "}",
        ".table-beta, .table-beta > th, .table-beta > td {",
        "    background-color: #395460;",
        "}",
        ".table-hover .table-beta:hover {",
        "    background-color: #4b7081;",
        "}",
        ".table-hover .table-beta:hover > td, .table-hover .table-beta:hover > th {",
        "    background-color: #4b7081;",
        "}",
        ".table-beta-dark, .table-beta-dark > th, .table-beta-dark > td {",
        "    background-color: #425157;",
        "}",
        ".table-hover .table-beta-dark:hover {",
        "    background-color: #586c74;",
        "}",
       " .table-hover .table-beta-dark:hover > td, .table-hover .table-beta-dark:hover > th {",
        "    background-color: #586c74;",
        "}",
        ".table-beta-light, .table-beta-light > th, .table-beta-light > td {",
        "    background-color: #325667;",
        "}",
        ".table-hover .table-beta-light:hover {",
        "    background-color: #42738a;",
        "}",
       " .table-hover .table-beta-light:hover > td, .table-hover .table-beta-light:hover > th {",
        "    background-color: #42738a;",
        "}",
        ".table-beta-lightest, .table-beta-lightest > th, .table-beta-lightest > td {",
        "    background-color: #275a72;",
        "}",
        ".table-hover .table-beta-lightest:hover {",
        "    background-color: #347898;",
        "}",
        ".table-hover .table-beta-lightest:hover > td, .table-hover .table-beta-lightest:hover > th {",
        "    background-color: #347898;",
        "}",
        ".table-gamma, .table-gamma > th, .table-gamma > td {",
        "    background-color: #801920;",
        "}",
        ".table-hover .table-gamma:hover {",
        "    background-color: #aa222b;",
        "}",
        ".table-hover .table-gamma:hover > td, .table-hover .table-gamma:hover > th {",
        "    background-color: #aa222b;",
        "}",
        ".table-gamma-dark, .table-gamma-dark > th, .table-gamma-dark > td {",
        "    background-color: #683133;",
        "}",
        ".table-hover .table-gamma-dark:hover {",
        "    background-color: #8b4144;",
        "}",
        ".table-hover .table-gamma-dark:hover > td, .table-hover .table-gamma-dark:hover > th {",
        "    background-color: #8b4144;",
        "}",
        ".table-gamma-light, .table-gamma-light > th, .table-gamma-light > td {",
        "    background-color: #950410;",
        "}",
        ".table-hover .table-gamma-light:hover {",
        "    background-color: #c70515;",
        "}",
        ".table-hover .table-gamma-light:hover > td, .table-hover .table-gamma-light:hover > th {",
        "    background-color: #c70515;",
        "}",
        ".table-gamma-lightest, .table-gamma-lightest > th, .table-gamma-lightest > td {",
        "    background-color: #94050e;",
        "}",
        ".table-hover .table-gamma-lightest:hover {",
        "    background-color: #c60613;",
        "}",
        ".table-hover .table-gamma-lightest:hover > td, .table-hover .table-gamma-lightest:hover > th {",
        "    background-color: #c60613;",
        "}",
        ".table-delta, .table-delta > th, .table-delta > td {",
        "    background-color: #434356;",
        "}",
        ".table-hover .table-delta:hover {",
        "    background-color: #5a5a72;",
        "}",
        ".table-hover .table-delta:hover > td, .table-hover .table-delta:hover > th {",
        "    background-color: #5a5a72;",
        "}",
        ".table-delta-dark, .table-delta-dark > th, .table-delta-dark > td {",
        "    background-color: #484851;",
        "}",
        ".table-hover .table-delta-dark:hover {",
        "    background-color: #60606c;",
        "}",
        ".table-hover .table-delta-dark:hover > td, .table-hover .table-delta-dark:hover > th {",
        "    background-color: #60606c;",
        "}",
        ".table-delta-light, .table-delta-light > th, .table-delta-light > td {",
        "    background-color: #3f3f5a;",
        "}",
        ".table-hover .table-delta-light:hover {",
        "    background-color: #555577;",
        "}",
        ".table-hover .table-delta-light:hover > td, .table-hover .table-delta-light:hover > th {",
        "    background-color: #555577;",
        "}",
        ".table-delta-lightest, .table-delta-lightest > th, .table-delta-lightest > td {",
        "    background-color: #393960;",
        "}",
        ".table-hover .table-delta-lightest:hover {",
        "    background-color: #4b4b81;",
        "}",
        ".table-hover .table-delta-lightest:hover > td, .table-hover .table-delta-lightest:hover > th {",
        "    background-color: #4b4b81;",
        "}",
        ".table-epsilon, .table-epsilon > th, .table-epsilon > td {",
        "    background-color: #7d361c;",
        "}",
        ".table-hover .table-epsilon:hover {",
        "    background-color: #a74825;",
        "}",
        ".table-hover .table-epsilon:hover > td, .table-hover .table-epsilon:hover > th {",
        "    background-color: #a74825;",
        "}",
        ".table-epsilon-dark, .table-epsilon-dark > th, .table-epsilon-dark > td {",
        "    background-color: #6a3e2f;",
        "}",
        ".table-hover .table-epsilon-dark:hover {",
        "    background-color: #8d533f;",
        "}",
        ".table-hover .table-epsilon-dark:hover > td, .table-hover .table-epsilon-dark:hover > th {",
        "    background-color: #8d533f;",
        "}",
        ".table-epsilon-light, .table-epsilon-light > th, .table-epsilon-light > td {",
        "    background-color: #8e2e0b;",
        "}",
        ".table-hover .table-epsilon-light:hover {",
        "    background-color: #be3d0e;",
        "}",
        ".table-hover .table-epsilon-light:hover > td, .table-hover .table-epsilon-light:hover > th {",
        "    background-color: #be3d0e;",
        "}",
        ".table-epsilon-lightest, .table-epsilon-lightest > th, .table-epsilon-lightest > td {",
        "    background-color: #992900;",
        "}",
        ".table-hover .table-epsilon-lightest:hover {",
        "    background-color: #cc3600;",
        "}",
        ".table-hover .table-epsilon-lightest:hover > td, .table-hover .table-epsilon-lightest:hover > th {",
        "    background-color: #cc3600;",
        "}",
        ".table .thead-dark th {",
        "    color: #a6a6a6;", 
        "    background-color: #171a1c;", 
        "    border-color: #2d3339;", 
        "}",
        ".table .thead-light th {",
        "    color: #9da8af;",
        "    background-color: #151a1e;",
        "    border-color: #2c333a;",
        "}",
        ".table-dark {",
        "    color: #a6a6a6;",
        "    background-color: #171a1c;",
        "}",
        ".table-dark th, .table-dark td, .table-dark thead th {",
        "    border-color: #2d3339;",
        "}",
        ".form-control{",
        "    color: #9ea6ae;",
        "    background-color: #1a1a1a;",
        "    border-color: #2c333a;",
        "}",
        ".form-control:focus{",
        "    color: #9ea6ae;",
        "    background-color: #1a1a1a;",
        "    border-color: #006664;",
        "}",
        ".form-control:disabled, .form-control[readonly]{",
        "    background-color: #a0a6ac;",
        "}",
        ".form-control::placeholder{",
        "    color: #97a6b4;",
        "}",
        "select.form-control:focus::-ms-value {",
        "    color: #9ea6ae;",
        "    background-color: #1a1a1a;",
        "}",
        ".form-control-plaintext{",
        "    color: #a6a6a6;",
        "}",
        ".form-check-input:disabled ~ .form-check-label{",
        "    color: #9ca6b0;",
        "}",
        ".valid-feedback{",
        "    color: #4dffa0;",
        "}",
        ".valid-tooltip{",
        "    color: #a6a6a6;",
        "    background-color: rgba(77, 255, 160, 0.9);",
        "}",
        ".was-validated .form-control:valid, .form-control.is-valid, .was-validated .custom-select:valid, .custom-select.is-valid {",
        "    color: #4dffa0;",
        "}",
        ".was-validated .form-control:valid:focus, .form-control.is-valid:focus, .was-validated .custom-select:valid:focus, .custom-select.is-valid:focus {",
        "    border-color: #4dffa0;",
        "    box-shadow: 0 0 0 0.2rem rgba(77, 255, 160, 0.25);",
        "}",
        ".was-validated .form-check-input:valid ~ .form-check-label, .form-check-input.is-valid ~ .form-check-label {",
        "    color: #4dffa0;",
        "}",
        ".was-validated .custom-control-input:valid ~ .custom-control-label, .custom-control-input.is-valid ~ .custom-control-label {",
        "    color: #4dffa0;",
        "}",
        ".was-validated .custom-control-input:valid ~ .custom-control-label::before, .custom-control-input.is-valid ~ .custom-control-label::before {",
        "    background-color: #003318;",
        "}",
        ".was-validated .custom-control-input:valid:checked ~ .custom-control-label::before, .custom-control-input.is-valid:checked ~ .custom-control-label::before {",
        "    background-color: #006630;",
        "}",
        ".was-validated .custom-control-input:valid:focus ~ .custom-control-label::before, .custom-control-input.is-valid:focus ~ .custom-control-label::before {",
        "    box-shadow: 0 0 0 1px #a6a6a6,0 0 0 0.2rem rgba(77, 255, 160, 0.25);",
        "}",
        ".was-validated .custom-file-input:valid ~ .custom-file-label, .custom-file-input.is-valid ~ .custom-file-label {",
        "    border-color: #006630;",
        "}",
        ".was-validated .custom-file-input:valid:focus ~ .custom-file-label, .custom-file-input.is-valid:focus ~ .custom-file-label {",
        "    box-shadow: 0 0 0 0.2rem rgba(77, 255, 160, 0.25);",
        "}",
        ".invalid-feedback{",
        "    color: #de716e;",
        "}",
        ".invalid-tooltip{",
        "    color: #a6a6a6;",
        "    background-color: rgba(42, 11, 9, 0.9);",
        "}",
        ".was-validated .form-control:invalid, .form-control.is-invalid, .was-validated .custom-select:invalid, .custom-select.is-invalid{",
        "    color: #de716e;",
        "}",
        ".was-validated .form-control:invalid:focus, .form-control.is-invalid:focus, .was-validated .custom-select:invalid:focus, .custom-select.is-invalid:focus {",
        "    border-color: #de716e;",
        "    box-shadow: 0 0 0 0.2rem rgba(42, 11, 9, 0.25);",
        "}",
        ".was-validated .form-check-input:invalid ~ .form-check-label, .form-check-input.is-invalid ~ .form-check-label {",
        "    color: #de716e;",
        "}",
        ".was-validated .custom-control-input:invalid ~ .custom-control-label, .custom-control-input.is-invalid ~ .custom-control-label {",
        "    color: #de716e;",
        "}",
        ".was-validated .custom-control-input:invalid ~ .custom-control-label::before, .custom-control-input.is-invalid ~ .custom-control-label::before {",
        "    background-color: #2a0a09;",
        "}",
        ".was-validated .custom-control-input:invalid:checked ~ .custom-control-label::before, .custom-control-input.is-invalid:checked ~ .custom-control-label::before {",
        "    background-color: #541512;",
        "}",
        ".was-validated .custom-control-input:invalid:focus ~ .custom-control-label::before, .custom-control-input.is-invalid:focus ~ .custom-control-label::before  {",
        "    box-shadow: 0 0 0 1px #a6a6a6,0 0 0 0.2rem rgba(42, 11, 9, 0.25);",
        "}",
        ".was-validated .custom-file-input:invalid ~ .custom-file-label, .custom-file-input.is-invalid ~ .custom-file-label {",
        "    border-color: #de716e;",
        "}",
        ".was-validated .custom-file-input:invalid:focus ~ .custom-file-label, .custom-file-input.is-invalid:focus ~ .custom-file-label {",
        "    box-shadow: 0 0 0 0.2rem rgba(42, 11, 9, 0.25);",
        "}",
        ".btn:focus, .btn.focus {",
        "    box-shadow: 0 0 0 0.2rem rgba(77, 255, 252, 0.25);",
        "}",
        ".btn-primary{",
        "    color: #1a1a1a;",
        "    background-color: #00b3b0;",
        "    border-color: #00b3b0;",
        "}",
        ".btn-primary:hover{",
        "    color: #1a1a1a;",
        "    background-color: #008784;",
        "    border-color: #006664;",
        "}",
        ".btn-primary:focus, .btn-primary.focus {",
        "    box-shadow: 0 0 0 0.2rem rgba(0, 179, 176, 0.5);",
        "}",
        ".btn-primary.disabled, .btn-primary:disabled{",
        "    color: #1a1a1a;",
        "    background-color: #00b3b0;",
        "    border-color: #00b3b0;",
        "}",
        ".btn-primary:not(:disabled):not(.disabled):active, .btn-primary:not(:disabled):not(.disabled).active, .show > .btn-primary.dropdown-toggle {",
        "    color: #1a1a1a;",
        "    background-color: #003332;",
        "    border-color: #006664;",
        "}",
        ".btn-primary:not(:disabled):not(.disabled):active:focus, .btn-primary:not(:disabled):not(.disabled).active:focus, .show > .btn-primary.dropdown-toggle:focus {",
        "    box-shadow: 0 0 0 0.2rem rgba(0, 179, 176, 0.5);",
        "}",
        ".btn-secondary{",
        "    color: #1a1a1a;",
        "    background-color: #a0a6ac;",
        "    border-color: #a0a6ac;",
        "}",
        ".btn-secondary:hover{",
        "    color: #1a1a1a;",
        "    background-color: #a0a7ac;",
        "    border-color: #9fa6ad;",
        "}",
        ".btn-secondary:focus, .btn-secondary.focus {",
        "    box-shadow: 0 0 0 0.2rem rgba(160, 166, 172, 0.5);",
        "}",
        ".btn-secondary.disabled, .btn-secondary:disabled{",
        "    color: #1a1a1a;",
        "    background-color: #a0a6ac;",
        "    border-color: #a0a6ac;",
        "}",
        ".btn-secondary:not(:disabled):not(.disabled):active, .btn-secondary:not(:disabled):not(.disabled).active, .show > .btn-secondary.dropdown-toggle {",
        "    color: #1a1a1a;",
        "    background-color: #9fa6ad;",
        "    border-color: #9fa6ad;",
        "}",
        ".btn-secondary:not(:disabled):not(.disabled):active:focus, .btn-secondary:not(:disabled):not(.disabled).active:focus, .show > .btn-secondary.dropdown-toggle:focus {",
        "    box-shadow: 0 0 0 0.2rem rgba(160, 166, 172, 0.5);",
        "}",
        //success, info, warning, danger, light, dark, default, violet, voilet-dark, violet-darker, inverse-lightest, inverse-light, inverse, 
        //inverse-dark, inverse-darker, alpha, alpha-dark, alpha-light, alpha-lightest, ... (beta, gamma, delta, epsilon)
        //outine-primary, outline-secondary,...
        //
        ".btn-link {",
        "    color: #00b3b0;",
        "}",
        ".btn-link:hover{",
        "    color: #008784;",
        "}",
        ".btn-link:disabled, .btn-link.disabled{",
        "    color: #c8ccd0;",
        "}",
        ".dropdown-menu{",
        "    color: #a6a6a6;",
        "    border-color: #6e8091;",
        "}",
        ".dropdown-divider{",
        "    border-color: #6e8091;",
        "}",
        ".dropdown-item{",
        "    color: #a6a6a6;",
        "}",
        ".dropdown-item:hover, .dropdown-item:focus {",
        "    color: #9ca6b0;",
        "    background-color: #2b333b;",
        "}",
        ".dropdown-item.active, .dropdown-item:active {",
        "    color: #9ca6b0;",
        "    background-color: #99a6b2;",
        "}",
        ".dropdown-item.disabled, .dropdown-item:disabled {",
        "    color: #d6d9db;",
        "}",
        ".dropdown-header {",
        "    color: #d6d9db;",
        "}",
        ".dropdown-item-text {",
        "    color: #a6a6a6;",
        "}",
        ".input-group-text {",
        "    color: #9ea6ae;",
        "    background-color: #151a1e;",
        "    border-color: #2b333b;",
        "}",
        ".custom-control-input:checked ~ .custom-control-label::before {",
        "    color: #97a6b4;",
        "    background-color: #151a1e;",
        "}",
        ".custom-control-input:focus ~ .custom-control-label::before {",
        "    box-shadow: 0 0 0 1px #d9d9d9, 0 0 0 0.2rem rgba(0, 179, 176, 0.25);",
        "}",
        ".custom-control-input:active ~ .custom-control-label::before {",
        "    color: #97a6b4;",
        "    background-color: #006664;",
        "}",
        ".custom-control-input:disabled ~ .custom-control-label {",
        "    color: #a0a6ac;",
        "}",
        ".custom-control-input:disabled ~ .custom-control-label::before {",
        "    background-color: #151a1e;",
        "}",
        ".custom-control-label::before {",
        "    background-color: #2c333a;",
        "}",
        ".custom-checkbox .custom-control-input:checked ~ .custom-control-label::before {",
        "    background-color: #00b3b0;",
        "}",
        ".custom-checkbox .custom-control-input:indeterminate ~ .custom-control-label::before {",
        "    background-color: #00b3b0;",
        "}",
        ".custom-checkbox .custom-control-input:disabled:checked ~ .custom-control-label::before {",
        "    background-color: rgba(0, 179, 176, 0.5);",
        "}",
        ".custom-checkbox .custom-control-input:disabled:indeterminate ~ .custom-control-label::before {",
        "    background-color: rgba(0, 179, 176, 0.5);",
        "}",
        ".custom-radio .custom-control-input:checked ~ .custom-control-label::before {",
        "    background-color: #00b3b0;",
        "}",
        ".custom-radio .custom-control-input:disabled:checked ~ .custom-control-label::before {",
        "    background-color: rgba(0, 179, 176, 0.5);",
        "}",
        ".custom-select {",
        "    color: ;",
        "    background: #000 url(\"data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 4 5'%3E%3Cpath fill='%23343a40' d='M2 0L0 2h4zm0 5L0 3h4z'/%3E%3C/svg%3E\") no-repeat right 0.75rem center;",
        "    border: 1px solid #161a1d;",
        "}",
        //TODO: include svg
    ].join("\n");
if (typeof GM_addStyle != "undefined") {
    GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
    PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
    addStyle(css);
} else {
    var node = document.createElement("style");
    node.type = "text/css";
    node.appendChild(document.createTextNode(css));
    var heads = document.getElementsByTagName("head");
    if (heads.length > 0) {
        heads[0].appendChild(node);
    } else {
        // no head yet, stick it whereever
        document.documentElement.appendChild(node);
    }
}
})();